### ISSUE TITLE
"WindowsError: [Error 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by the-shank** [kennethreitz/legit#148]
I am getting the above error whenever I try running any legit command. Here is the ouput from the terminal.

```
C:\Users\6008321\git\requisition-tool>legit sync
Traceback (most recent call last):
File "C:\Python27\Scripts\legit-script.py", line 9, in <module>
    load_entry_point('legit==0.1.1', 'console_scripts', 'legit')()
File "C:\Python27\lib\site-packages\legit\cli.py", line 45, in main
    cmd_map.get(arg).__call__(args)
File "C:\Python27\lib\site-packages\legit\cli.py", line 155, in cmd_sync
    if repo.is_dirty():
File "C:\Python27\lib\site-packages\git\repo\base.py", line 502, in is_dirty
    len(self.git.diff('HEAD', '--cached', *default_args)):
File "C:\Python27\lib\site-packages\git\cmd.py", line 227, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
File "C:\Python27\lib\site-packages\git\cmd.py", line 456, in _call_process
    return self.execute(call, **_kwargs)
File "C:\Python27\lib\site-packages\git\cmd.py", line 335, in execute
    **subprocess_kwargs
File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I am on Windows 7.

**Comment by Soobrakay** [comment]
New version of git for windows (I have 2.9.3) installs git.exe instead of git.cmd, so this shouldn't happen with newer version.

Additionally, a user can select to install Git + optional Unix tools on the path, and that also puts git.exe on the path for older versions.
