### ISSUE TITLE
Install seems broken

### ISSUE THREAD

**Issue by tschellenbach** [kennethreitz/legit#152]
pip install

ownloading/unpacking gitpython>=0.3.0 (from legit)
  Could not find a version that satisfies the requirement gitpython>=0.3.0 (from legit) (from versions: 0.1.7, 0.2.0-beta1, 0.3.0-beta1, 0.3.0-beta2, 0.3.1-beta2, 0.3.2.RC1)
Cleaning up...
No distributions matching the version for gitpython>=0.3.0 (from legit)
Storing debug log for failure in /home/thierry/.pip/pip.log
(stream)thierry@thierry-XPS-8300:~/workspace/stream$ legit install
Traceback (most recent call last):
  File "/usr/bin/legit", line 9, in <module>
    load_entry_point('legit==0.1.1', 'console_scripts', 'legit')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/legit/cli.py", line 15, in <module>
    from clint import args
ImportError: cannot import name args

**Comment by mancvso** [comment]
I can confirm this bug. My log:

```
 $ legit install 
Traceback (most recent call last):
  File "/usr/local/bin/legit", line 9, in <module>
    load_entry_point('legit==0.1.1', 'console_scripts', 'legit')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/legit/cli.py", line 15, in <module>
    from clint import args
ImportError: cannot import name args
```

**Comment by airtonix** [comment]
still broken. lesigh.

**Comment by mancvso** [comment]
If you install from git zip fil, it works.
```
sudo pip install http://github.com/kennethreitz/legit/archive/develop.zip
```

**Comment by gsakkis** [comment]
If you install from pip this fixes it:

    pip install 'clint<0.3.2'

**Comment by realhu1989** [comment]
change clint version to 0.3.1 should fix it , I just tryed.

**Comment by hickford** [comment]
Fixed by https://github.com/kennethreitz/legit/commit/c19e91617d9ff46a4a0abd1b4b31deb1313406a6 ?

Try installing from develop:

    pip install git+https://github.com/kennethreitz/legit.git@develop

Does that install correctly? Otherwise please reopen the issue
