### ISSUE TITLE
ValueError: Remote-Section has invalid format: u'remote'

### ISSUE THREAD

**Issue by jmartinm** [kennethreitz/legit#195]
Just installed `legit==0.2.0` via Pypi on Mac OSX and I am getting the following error:

``` python
$ legit branches
Traceback (most recent call last):
  File "/bin/legit", line 7, in <module>
    from legit.cli import main
  File "/lib/python2.7/site-packages/legit/cli.py", line 27, in <module>
    from .scm import *
  File "/lib/python2.7/site-packages/legit/scm.py", line 283, in <module>
    remote = get_remote()
  File "/lib/python2.7/site-packages/legit/scm.py", line 220, in get_remote
    repo_check(require_remote=True)
  File "/lib/python2.7/site-packages/legit/scm.py", line 50, in repo_check
    if not repo.remotes and require_remote:
  File "/lib/python2.7/site-packages/git/repo/base.py", line 266, in remotes
    return Remote.list_items(self)
  File "/lib/python2.7/site-packages/git/util.py", line 717, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/lib/python2.7/site-packages/git/remote.py", line 433, in iter_items
    raise ValueError("Remote-Section has invalid format: %r" % section)
ValueError: Remote-Section has invalid format: u'remote'
```

``` bash
$ git --version
git version 2.6.2
```

**Comment by wkentaro** [comment]
you can check `.git/config`.
I added `[remote]` and reproduces the error.

```
% cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[branch "master"]
[remote]  # I added this line

% legit branches
Traceback (most recent call last):
  File "/usr/local/bin/legit", line 7, in <module>
    from legit.cli import main
  File "/usr/local/lib/python2.7/dist-packages/legit/cli.py", line 27, in <module>
    from .scm import *
  File "/usr/local/lib/python2.7/dist-packages/legit/scm.py", line 283, in <module>
    remote = get_remote()
  File "/usr/local/lib/python2.7/dist-packages/legit/scm.py", line 220, in get_remote
    repo_check(require_remote=True)
  File "/usr/local/lib/python2.7/dist-packages/legit/scm.py", line 50, in repo_check
    if not repo.remotes and require_remote:
  File "/usr/local/lib/python2.7/dist-packages/git/repo/base.py", line 266, in remotes
    return Remote.list_items(self)
  File "/usr/local/lib/python2.7/dist-packages/git/util.py", line 717, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 433, in iter_items
    raise ValueError("Remote-Section has invalid format: %r" % section)
ValueError: Remote-Section has invalid format: u'remote'
```

**Comment by wkentaro** [comment]
It should be like:
```
[remote "origin"]
	url = git@github.com:wkentaro/jskeus.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by weakish** [comment]
Closed since this seems to be an configuration error on `.git/config`
