### ISSUE TITLE
Installing with pip fails

### ISSUE THREAD

**Issue by garann** [kennethreitz/legit#50]
When trying to install legit using pip, I get an error and the installation fails. Error is pasted below. I've never used pip before, so I'm just leaving it here in hopes that it's useful.

Thanks!

---

/usr/bin/pip run on Mon Apr  2 16:44:27 2012
Downloading/unpacking legit

  Running setup.py egg_info for package legit

```
/home/gmeans/build/legit/setup.py:19: Warning: 'with' will become a reserved keyword in Python 2.6

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/gmeans/build/legit/setup.py", line 19

    with open('reqs.txt') as f:

            ^

SyntaxError: invalid syntax

Complete output from command python setup.py egg_info:

/home/gmeans/build/legit/setup.py:19: Warning: 'with' will become a reserved keyword in Python 2.6
```

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/gmeans/build/legit/setup.py", line 19

```
with open('reqs.txt') as f:

        ^
```

SyntaxError: invalid syntax

---

Command python setup.py egg_info failed with error code 1 in /home/gmeans/build/legit

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/pip-1.1.post1-py2.5.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.5/site-packages/pip-1.1.post1-py2.5.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.5/site-packages/pip-1.1.post1-py2.5.egg/pip/req.py", line 1015, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.5/site-packages/pip-1.1.post1-py2.5.egg/pip/req.py", line 226, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.5/site-packages/pip-1.1.post1-py2.5.egg/pip/**init**.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/gmeans/build/legit

**Comment by weakish** [comment]
Python 2.5 is not supported.
