### ISSUE TITLE
git-legit.org is missing the second argument for git graft

### ISSUE THREAD

**Issue by kentbrew** [kennethreitz/legit#61]
$ git graft &lt;branch>
Merge unpublished branch into current branch, then remove it.

This blows up, apparently because I am failing to say which branch I want to graft my new branch (yay) into:

mybox:myrepo kentbrew$ git graft yay
Switching to yay.
Grafting yay into yay.
Traceback (most recent call last):
  File "/usr/local/bin/legit", line 8, in &lt;module>
    load_entry_point('legit==0.1.1', 'console_scripts', 'legit')()
  File "/Library/Python/2.7/site-packages/legit/cli.py", line 45, in main
    cmd_map.get(arg).**call**(args)
  File "/Library/Python/2.7/site-packages/legit/cli.py", line 247, in cmd_graft
    colored.yellow(branch), colored.yellow(into_branch)), branch)
  File "/Library/Python/2.7/site-packages/legit/cli.py", line 80, in status_log
    log = func(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/legit/scm.py", line 185, in graft_branch
    out = repo.git.execute([git, 'branch', '-D', branch])
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 377, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git branch -D yay' returned exit status 1: error: Cannot delete the branch 'yay' which you are currently on.

This works like a champ:

mybox:myrepo kentbrew$ git graft yay master

Switching to master.
Grafting yay into master.
Merge made by the 'recursive' strategy.
 woo.txt |    2 ++
 yay.txt |    2 ++
 2 files changed, 4 insertions(+)
 create mode 100644 woo.txt
 create mode 100644 yay.txt
Deleted branch yay (was 373d97a).

**Comment by weakish** [comment]
Close this since the graft command has been removed.
