### ISSUE TITLE
git sync failed

### ISSUE THREAD

**Issue by neilmiddleton** [kennethreitz/legit#63]
No real idea as to why but the trace is here:

Pushing commits to the server.
Restoring local changes.
Traceback (most recent call last):
  File "/usr/local/bin/legit", line 9, in <module>
    load_entry_point('legit==0.1.1', 'console_scripts', 'legit')()
  File "/Library/Python/2.7/site-packages/legit/cli.py", line 45, in main
    cmd_map.get(arg).**call**(args)
  File "/Library/Python/2.7/site-packages/legit/cli.py", line 162, in cmd_sync
    status_log(unstash_it, 'Restoring local changes.', sync=True)
  File "/Library/Python/2.7/site-packages/legit/cli.py", line 80, in status_log
    log = func(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/legit/scm.py", line 99, in unstash_it
    'stash', 'pop', 'stash@{{0}}'.format(stash_index)])
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 377, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git stash pop stash@{0}' returned exit status 1:

**Comment by weakish** [comment]
duplicated by #35
