### ISSUE TITLE
legit sync prints stack trace if not in a git repository

### ISSUE THREAD

**Issue by AaronSikes** [kennethreitz/legit#99]
```bash
~$ legit sync
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 45, in main
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 147, in cmd_sync
AttributeError: 'NoneType' object has no attribute 'head'
```

A warning would be preferable, yes?

**Comment by wkentaro** [comment]
Should be fixed by #174 .
Please close.
